// Static JSON loader for community hot posts.
// Generated by .github/workflows/fetch-community-hot.yml

export interface CommunityHotPost {
  id: string;
  external_id: string;
  source: string;
  title: string;
  url: string;
  thumbnail_url: string | null;
  description: string | null;
  author: string | null;
  posted_at: string;
  fetched_at: string;
}

export interface CommunityHotFile {
  generated_at: string;
  count: number;
  posts: CommunityHotPost[];
}

let _cache: CommunityHotFile | null = null;

export async function loadCommunityHot(): Promise<CommunityHotFile> {
  if (_cache) return _cache;
  const base = import.meta.env.BASE_URL || "/";
  const url = `${base.replace(/\/$/, "")}/community-hot.json`;
  const res = await fetch(url, { cache: "no-store" });
  if (!res.ok) throw new Error(`Failed to load community-hot.json (${res.status})`);
  const data = (await res.json()) as CommunityHotFile;
  _cache = data;
  return data;
}

export function clearCommunityHotCache() {
  _cache = null;
}

export const SOURCE_LABEL: Record<string, string> = {
  clien: "클리앙",
  todayhumor: "오늘의유머",
  reddit: "Reddit",
};
